#!/usr/bin/env bash
cd /persistent/server
set -eo pipefail

SERVER_ARGUMENTS=$(xargs < /etc/nimc/server.arguments)
PID_FILE="/run/nimc/server.pid"
INACTIVITY_FILE="/run/nimc/server.inactive"

JAVA="/persistent/bin/java"

# Make sure that `java` is installed
if [ ! -x "$JAVA" ]; then
  echo "java not found at $JAVA! Aborting."
  exit 1
fi

# Try to find server jar
shopt -s nullglob
JARS=(*.jar)
shopt -u nullglob
if [ ${#JARS[@]} -eq 0 ]; then
  echo "No .jar file found! Aborting."
  exit 1
fi
SERVER_JAR="${JARS[0]}"
echo "Server is $SERVER_JAR"

# Check if server is already running
if [ -f "$PID_FILE" ]; then
  if kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
    echo "Minecraft server already running with PID $(cat "$PID_FILE")"
    exit 1
  else
    echo "Stale PID file found. Removing."
    rm -f "$PID_FILE"
  fi
fi

# Remove the possibly existing old "Server inactive" file
rm -f "$INACTIVITY_FILE"

# Start the server in the background and save its PID
$JAVA $SERVER_ARGUMENTS -jar "$SERVER_JAR" nogui &
echo "$!" > "$PID_FILE"

# Wait a bit and check if the process is still running
sleep 5
if ! kill -0 "$(cat "$PID_FILE")" 2>/dev/null; then
  echo "Failed to start Minecraft server."
  rm -f "$PID_FILE"
  exit 1
fi

echo "Minecraft server started successfully."
