#!/usr/bin/env bash
cd /persistent/server
set -eo pipefail

PID_FILE="/run/nimc/server.pid"
INACTIVITY_FILE="/run/nimc/server.inactive"
TIMEOUT=30

RCON="/persistent/bin/rcon"

# Make sure that `rcon` is installed
if [ ! -x "$RCON" ]; then
  echo "rcon not found at $RCON! Aborting."
  exit 1
fi

# Read RCON configuration from `server.properties`
if [ ! -f "server.properties" ]; then
  echo "server.properties not found in $(pwd). Aborting."
  exit 1
fi

RCON_PORT="$(grep '^rcon.port=' server.properties | cut -d'=' -f2)"
RCON_PASSWORD="$(grep '^rcon.password=' server.properties | cut -d'=' -f2)"

# Stop Minecraft
$RCON -a "localhost:$RCON_PORT" -p "$RCON_PASSWORD" stop
echo "Stop command sent to localhost:${RCON_PORT}..."

# Sanity checks for PID
if [ ! -f "$PID_FILE" ]; then
  echo "No PID file found. Server has been launched manually."
  exit 1
fi

MINECRAFT_PID="$(cat "$PID_FILE")"
if ! kill -0 "$MINECRAFT_PID" 2>/dev/null; then
  echo "No running Minecraft server with PID $MINECRAFT_PID. Removing stale PID file."
  rm -f "$PID_FILE"
  exit 1
fi

# Wait until the dust settles...
while kill -0 "$MINECRAFT_PID" 2>/dev/null; do
  sleep 1
  TIMEOUT=$((TIMEOUT - 1))
  if [ $TIMEOUT -eq 0 ]; then
    echo "Server did not stop within timeout."
    exit 1
  fi
done

rm -f "$PID_FILE"
rm -f "$INACTIVITY_FILE"

echo "Minecraft server stopped gracefully."
